name: Build and deploy Node.js app to Azure Web App - opensource

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: |
          NODE_ENV=production npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .
          include-hidden-files: true

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B9D8F56CC42F49B5921C813891707F4C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_57C5439A02D142FBB46C5D2F0D0C93EF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DE49394836D04A90846098E1ABA526DA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: opensource
          slot-name: Production
          package: .
